Allow the key script to add hosts to the known_hosts file

diff --git a/bin/key b/bin/key
--- a/bin/key
+++ b/bin/key
@@ -1,9 +1,46 @@
 #!/bin/bash
 
-if [ ! -f "/.ssh/id_git.pub" ]; then
-  mkdir /.ssh
-  chmod 700 /.ssh
-  ssh-keygen -N '' -f /.ssh/id_git
-fi
+add() {
+  host=$1
 
-cat /.ssh/id_git.pub
+  if [ $host == "" ]; then
+    echo "Usage: key add {host}"
+    echo "  Adds the host key for a specific host to the SSH known hosts file"
+    exit 1
+  fi
+
+  touch /root/.ssh/known_hosts
+  out=$(ssh-keygen -F $host)
+  if [ -z "$out" ]; then
+    ip=$(dig +short $host)
+    if [ -z "$ip" ]; then
+      echo "Unable to resolve $ip"
+      exit 2
+    fi
+    ssh-keyscan -H $host >> /root/.ssh/known_hosts
+    ssh-keyscan -H $ip >> /root/.ssh/known_hosts
+  fi
+}
+
+gen() {
+  if [ ! -f "/.ssh/id_git.pub" ]; then
+    mkdir -p /root/.ssh
+    chmod 700 /root/.ssh
+    ssh-keygen -N '' -f /root/.ssh/id_git
+  fi
+
+  cat /root/.ssh/id_git.pub
+}
+
+case "$1" in
+  add)
+    add $1
+    ;;
+  gen)
+    gen
+    ;;
+  *)
+    echo "Usage: key {add|gen}"
+    exit 1
+  ;;
+esac
